# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'rubygems'
require 'bundler/setup'
require 'action_view'
require 'active_support'
require 'active_model'
require 'railsstrap'
require 'abstract_controller'
require 'action_controller'
require 'mocha/api'
require 'pry'
require 'rspec'
require 'rspec-html-matchers'

require 'coveralls'
Coveralls.wear!

RSpec.configure do |config|
  config.include RSpecHtmlMatchers
end